// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attach/{id}": {
            "get": {
                "tags": [
                    "Attachments"
                ],
                "summary": "Retrieve attachment file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Attachment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/chat": {
            "get": {
                "tags": [
                    "Chat"
                ],
                "summary": "List the current user chats",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of chats to skip.",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 9,
                        "description": "Number of chats to take.",
                        "name": "take",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Current user profile",
                        "schema": {
                            "$ref": "#/definitions/main.ChatsPageDto"
                        }
                    }
                }
            }
        },
        "/direct-chat": {
            "put": {
                "tags": [
                    "Chat"
                ],
                "summary": "Update direct chat with another user.",
                "parameters": [
                    {
                        "description": "Direct chat options.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateDirectChatDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Direct chat created.",
                        "schema": {
                            "$ref": "#/definitions/main.CreateChatResultDto"
                        }
                    },
                    "204": {
                        "description": "Changes applied to direct chat."
                    }
                }
            }
        },
        "/group-chat": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Create a group chat",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The name of the group",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "The description of the group",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Account IDs of the members",
                        "name": "accountIds",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Group picture",
                        "name": "picture",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The group is created.",
                        "schema": {
                            "$ref": "#/definitions/main.CreateChatResultDto"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Generates the access-token cookie.",
                "tags": [
                    "User"
                ],
                "summary": "Authenticate",
                "parameters": [
                    {
                        "description": "Authentication payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Commit unalive",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/logup": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create account",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LogupDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "See current user",
                "responses": {
                    "200": {
                        "description": "Current user profile",
                        "schema": {
                            "$ref": "#/definitions/main.ProfileResultDto"
                        }
                    }
                }
            }
        },
        "/post": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "Post"
                ],
                "summary": "Send a post in the chat.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Chat Id",
                        "name": "chatId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reply to Post ID",
                        "name": "replyToId",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Message",
                        "name": "message",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "Attachments (multiple files)",
                        "name": "attach",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "The post is posted.",
                        "schema": {
                            "$ref": "#/definitions/main.CreatePostResultDto"
                        }
                    }
                }
            }
        },
        "/profile-picture": {
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update profile picture",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Profile picture",
                        "name": "picture",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Remove profile picture",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of users to skip.",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 9,
                        "description": "Number of users to take.",
                        "name": "take",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Query by user name.",
                        "name": "query",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Users",
                        "schema": {
                            "$ref": "#/definitions/main.UsersPageDto"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ChatsPageDto": {
            "type": "object",
            "properties": {
                "chats": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "directInfo": {
                                "description": "Present only for direct chats.",
                                "type": "object",
                                "properties": {
                                    "himBlockedYou": {
                                        "type": "boolean"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "youBlockedHim": {
                                        "type": "boolean"
                                    }
                                }
                            },
                            "groupInfo": {
                                "description": "Present only for group chats.",
                                "type": "object",
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "youAreAdmin": {
                                        "type": "boolean"
                                    },
                                    "youAreOwner": {
                                        "type": "boolean"
                                    }
                                }
                            },
                            "id": {
                                "type": "string"
                            },
                            "isMuted": {
                                "type": "boolean"
                            },
                            "isPinned": {
                                "type": "boolean"
                            },
                            "lastPost": {
                                "type": "object",
                                "properties": {
                                    "fileCount": {
                                        "type": "integer"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "message": {
                                        "type": "string"
                                    },
                                    "postedAt": {
                                        "type": "string"
                                    },
                                    "poster": {
                                        "type": "object",
                                        "properties": {
                                            "id": {
                                                "type": "string"
                                            },
                                            "name": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            },
                            "pictureId": {
                                "type": "string"
                            },
                            "validFrom": {
                                "type": "string"
                            }
                        }
                    }
                },
                "counted": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "taken": {
                    "type": "integer"
                }
            }
        },
        "main.CreateChatResultDto": {
            "type": "object",
            "properties": {
                "chatId": {
                    "type": "string"
                }
            }
        },
        "main.CreatePostResultDto": {
            "type": "object",
            "properties": {
                "postId": {
                    "type": "string"
                }
            }
        },
        "main.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.LogupDto": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.ProfileResultDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pictureId": {
                    "type": "string"
                }
            }
        },
        "main.UpdateDirectChatDto": {
            "type": "object",
            "required": [
                "otherAccountId"
            ],
            "properties": {
                "doBlock": {
                    "type": "boolean"
                },
                "doFriend": {
                    "type": "boolean"
                },
                "doMute": {
                    "type": "boolean"
                },
                "doPin": {
                    "type": "boolean"
                },
                "otherAccountId": {
                    "type": "string"
                }
            }
        },
        "main.UsersPageDto": {
            "type": "object",
            "properties": {
                "counted": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                },
                "taken": {
                    "type": "integer"
                },
                "users": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "directInfo": {
                                "type": "object",
                                "properties": {
                                    "himBlockedYou": {
                                        "type": "boolean"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "isFriend": {
                                        "type": "boolean"
                                    },
                                    "isMuted": {
                                        "type": "boolean"
                                    },
                                    "isPinned": {
                                        "type": "boolean"
                                    },
                                    "youBlockedHim": {
                                        "type": "boolean"
                                    }
                                }
                            },
                            "id": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "pictureId": {
                                "type": "string"
                            },
                            "username": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "access-token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
