// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/direct-chat": {
            "put": {
                "tags": [
                    "Chat"
                ],
                "summary": "Update direct chat with another user.",
                "parameters": [
                    {
                        "description": "Direct chat options.",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.UpdateDirectChatDto"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Direct chat created.",
                        "schema": {
                            "$ref": "#/definitions/main.UpdateDirectChatResultDto"
                        }
                    },
                    "204": {
                        "description": "Changes applied to direct chat."
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Generates the access-token cookie.",
                "tags": [
                    "User"
                ],
                "summary": "Authenticate",
                "parameters": [
                    {
                        "description": "Authentication payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Commit unalive",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/logup": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Create account",
                "parameters": [
                    {
                        "description": "Account data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.LogupDto"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/me": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "See current user",
                "responses": {
                    "200": {
                        "description": "Current user profile",
                        "schema": {
                            "$ref": "#/definitions/main.ProfileResultDto"
                        }
                    }
                }
            }
        },
        "/profile-picture": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Retrieve profile picture",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "put": {
                "consumes": [
                    "multipart/form-data"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update profile picture",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Profile picture",
                        "name": "picture",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            },
            "delete": {
                "tags": [
                    "User"
                ],
                "summary": "Remove profile picture",
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        }
    },
    "definitions": {
        "main.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.LogupDto": {
            "type": "object",
            "required": [
                "name",
                "password",
                "username"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "main.ProfileResultDto": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "main.UpdateDirectChatDto": {
            "type": "object",
            "required": [
                "otherAccountId"
            ],
            "properties": {
                "doBlock": {
                    "type": "boolean"
                },
                "doFriend": {
                    "type": "boolean"
                },
                "doMute": {
                    "type": "boolean"
                },
                "doPin": {
                    "type": "boolean"
                },
                "otherAccountId": {
                    "type": "string"
                }
            }
        },
        "main.UpdateDirectChatResultDto": {
            "type": "object",
            "properties": {
                "chatId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "access-token",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
