definitions:
  main.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  main.LogupDto:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  main.ProfileResultDto:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      description: Generates the access-token cookie.
      parameters:
      - description: Authentication payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginDto'
      responses: {}
      summary: Authenticate
  /logout:
    post:
      responses:
        "204":
          description: No Content
      summary: Commit unalive
  /logup:
    post:
      parameters:
      - description: Account data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LogupDto'
      responses: {}
      summary: Create account
  /me:
    get:
      responses:
        "200":
          description: Current user profile
          schema:
            $ref: '#/definitions/main.ProfileResultDto'
      summary: See current user
securityDefinitions:
  CookieAuth:
    in: cookie
    name: access-token
    type: apiKey
swagger: "2.0"
