definitions:
  main.CreatePostResultDto:
    properties:
      postId:
        type: string
    type: object
  main.LoginDto:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  main.LogupDto:
    properties:
      name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - name
    - password
    - username
    type: object
  main.ProfileResultDto:
    properties:
      id:
        type: string
      name:
        type: string
    type: object
  main.UpdateDirectChatDto:
    properties:
      doBlock:
        type: boolean
      doFriend:
        type: boolean
      doMute:
        type: boolean
      doPin:
        type: boolean
      otherAccountId:
        type: string
    required:
    - otherAccountId
    type: object
  main.UpdateDirectChatResultDto:
    properties:
      chatId:
        type: string
    type: object
info:
  contact: {}
paths:
  /direct-chat:
    put:
      parameters:
      - description: Direct chat options.
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.UpdateDirectChatDto'
      responses:
        "201":
          description: Direct chat created.
          schema:
            $ref: '#/definitions/main.UpdateDirectChatResultDto'
        "204":
          description: Changes applied to direct chat.
      summary: Update direct chat with another user.
      tags:
      - Chat
  /login:
    post:
      description: Generates the access-token cookie.
      parameters:
      - description: Authentication payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LoginDto'
      responses:
        "204":
          description: No Content
      summary: Authenticate
      tags:
      - User
  /logout:
    post:
      responses:
        "204":
          description: No Content
      summary: Commit unalive
      tags:
      - User
  /logup:
    post:
      parameters:
      - description: Account data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LogupDto'
      responses:
        "204":
          description: No Content
      summary: Create account
      tags:
      - User
  /me:
    get:
      responses:
        "200":
          description: Current user profile
          schema:
            $ref: '#/definitions/main.ProfileResultDto'
      summary: See current user
      tags:
      - User
  /post:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Chat Id
        in: formData
        name: chatId
        required: true
        type: string
      - description: Reply to Post ID
        in: formData
        name: replyToId
        type: string
      - description: Message
        in: formData
        name: message
        type: string
      - collectionFormat: csv
        description: Attachments (multiple files)
        in: formData
        items:
          type: file
        name: attach
        type: array
      responses:
        "201":
          description: The post is posted.
          schema:
            $ref: '#/definitions/main.CreatePostResultDto'
      summary: Send a post in the chat.
      tags:
      - Chat
  /profile-picture:
    delete:
      responses:
        "204":
          description: No Content
      summary: Remove profile picture
      tags:
      - User
    get:
      responses:
        "200":
          description: OK
      summary: Retrieve profile picture
      tags:
      - User
    put:
      consumes:
      - multipart/form-data
      parameters:
      - description: Profile picture
        in: formData
        name: picture
        required: true
        type: file
      responses:
        "204":
          description: No Content
      summary: Update profile picture
      tags:
      - User
securityDefinitions:
  CookieAuth:
    in: cookie
    name: access-token
    type: apiKey
swagger: "2.0"
